##
# Example Ansible playbook that uses the PostgreSQL module.
#
# This installs PostgreSQL on an Ubuntu system and creates a database 
# named according to the variable in the group_vars common file.
#
---

- include: install_db_packages.yml
- include: config_database.yml

